### ISSUE TITLE
build errors on opensuse

### ISSUE THREAD

**Issue by spockfish** [Bareflank/hypervisor#132]
Guys,

I'm trying to get things rolling on openSUSE Tumbleweed. So far so good, but during build I'm getting this error:

/home/harry/dev/hypervisor/bfelf_loader/test/test.cpp:263:20: error: could not convert ‘false’ from ‘bool’ to ‘std::shared_ptr<char>’

Could you help out?

**Comment by rianquinn** [comment]
Huh.... yeah that code is wrong. It should return nullptr on both (there is more than one) "return false".

**Comment by rianquinn** [comment]
I merged a fix for your issue. Let me know if that helps. We have not tested OpenSUSE yet but it should work so long as you have a GCC compiler >= 4.9 and CMake >= 3.0. Let us know how it goes.

**Comment by spockfish** [comment]
Thanks! I'll try it out this weekend. I've got an setup-opensuse ready to be merged if it works. I'll keep you posted.

**Comment by rianquinn** [comment]
FYI, I should have a PR today that cleans up some of our script naming that will affect what your working on. Specifically, we are removing the "-" from the scripts in favor of "_". So the name of the setup script for OpenSUSE would be "setup_opensuse.sh".

**Comment by spockfish** [comment]
ok, no prob.

**Comment by rianquinn** [comment]
@spockfish this has been fixed in the following PR: https://github.com/Bareflank/hypervisor/pull/349

I updated the scripts to use a setup_common.sh to remove duplication, and the os-release info is now being used were possible. I also updated the script to use OpenSUSE Leap 42.2 instead of Tumbleweed as I would prefer to have a stable release to work from when possible. Although OpenSUSE takes a lot longer to install / compile Bareflank, it works great once it's all setup.
