### ISSUE TITLE
Guest enclave check

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#232]
Section 26.3.1.5 describes a check (the last one under interruptibility state) if the enclave interruption bit is set in the guest interruptibility state.  Should this check be implemented?

**Comment by rianquinn** [comment]
Yes, my guess is that's an SGX check, which I'm sure someone is going to want to play with at some point. Likely you will find a couple more that are missing as my manual must have been pre-Skylake. All the more reason why the code has to match the manual because we will likely have to review the docs for additions as each new architecture comes out.

**Comment by connojd** [comment]
Ok yep it is an SGX check

**Comment by connojd** [comment]
Fixed in #343
