### ISSUE TITLE
Failed unit tests in VMCS all have [99] as line number

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#245]
@connojd While working on the MSR changes, I ran into some of the VMCS unit tests failing, and they all have the same line number of [99] which makes is pretty hard to track down which function / line is belongs to the test that is failing.

**Comment by connojd** [comment]
As I mentioned in #209, since the tests run in a loop, you can trace the error back to a member of vmcs_ut, but then there are several possibilities for the test within the loop which is causing the failure. So any failures within the loop will be reported on the same line.

I think the easiest fix for this is to print the "what" from the caught exception vs the expecting exception in the expect functions so that the tester can search for that string in the test file and instantly know which path caused the error.

**Comment by rianquinn** [comment]
agreed

**Comment by connojd** [comment]
Fixed in #339

**Comment by rianquinn** [comment]
@connojd is this still and issue?

**Comment by connojd** [comment]
No but I can't close it
