### ISSUE TITLE
Adjust get() for secondary controls

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#256]
I think we need to check if `ia32_vmx_true_proc_based_ctls::activate_secondary_controls::get()` is one
along with the relevant secondary control.
So something like

``` cpp
...
namespace virtualize_apic_accesses
{
    ...
    inline auto get() noexcept
    { return ((__read_msr(addr) & mask) >> from) & ia32_vmx_true_procbased_ctls::activate_secondary_controls::get(); }
}
...
```

for each secondary control

**Comment by rianquinn** [comment]
Hmmmmm...

That certainly is needed in the `is_supported()` function. Basically, any control that uses the secondary controls should first check to see if secondary is supported at all. If you want to check for support, you should use `is_supported()` and if you fail to do that, `get()` / `set()` fill throw when you try as the `vmread` / `vmwrite` will fail. Not sure if I want to run `is_supported()` inside of `get()` / `set()` as it is likely not always needed. 

Thoughts?

**Comment by connojd** [comment]
Ok so for each vmcs field that requires a secondary processor control to be set, the corresponding `is_supported()` in the field's namespace will return `ia32_vmx_true_procbased_ctls::activate_secondary_controls::get() == 1`
and `is_enabled()` will return
`is_supported() && ia32_vmx_procbased_ctls2::<control_name>::get() == 1`?

**Comment by rianquinn** [comment]
I don't think we need an is enabled anymore as it's basically just `vmcs::xxx_ctrl::field::get()`. 

`is_supported` would be coded like this:

```
\\ Anything without a *
bool is_supported() 
{ return true; }

\\ All ctrls minus the secondary ones
bool is_supported() 
{ return msr::xxx_ctrl::field::get() == 1; } 

\\ Secondary ones
bool is_supported() 
{ return msr::proc_ctrl::secondary::get() == 1 && msr::xxx_ctrl::field::get() == 1; } 
```

That's it, if you want to know if secondary has been enabled, use the example I gave above, as it's more explicit what your trying to do.

**Comment by connojd** [comment]
I'm normally not this pedantic, but since one of the goals of transitioning to namespaces is for a more precise correspondence to how the manual reads, I'm going to explain what I think.  

First, vmcs fields either exist or they don't, so `exists()` would be better than `is_supported()` for the vmcs namespace, since that matches the language used in the manual. Second, a secondary control that is supported does not imply that it is enabled. The code above suggests supported does imply enabled, and I think that makes what the code does more obfuscated rather than explicit.

The secondary controls' current `get()` functions have no meaning to clients of those functions.  Clients must make a separate call to see if the secondary controls are activated, when I believe that logic should be handled in the implemenation of the secondary controls' `get()`.

**Comment by rianquinn** [comment]
I like pedantic so bring it on 😄 

You are right (I just checked), and it does say "exists", so I agree, we should change that now while we still have a chance. 

You are also right that `exists()` doesn't imply enabled. I am fine with your proposed implementation, but I think we should get some more input from @brendank310 (or anyone else whose watching this) before deciding. 

Basically.... what's being proposed here is for secondary controls `set()` and `get()`. When you `set()` we could automatically enable the secondary controls for you, or we could toss up a warning reminding the developer that the secondary controls have not be enabled when trying to enable one of them. I think for `get()`, you have a bigger issue if feature is actually enabled, but secondary controls have not been. @connojd's proposed approach would return `0` even though the bit is actually set in this case, and simply secondary controls have not been causing an inconsistency. 

Personally I am in favor of the developer having to manually enable secondary controls so that everything is explicit, and we simply toss up a warning, but I'd be fine with @connojd's approach too depending on what other's say.

**Comment by brendank310** [comment]
I like exists(), that seems like a clear way of indicating the control's availability. If the control fields are always simply one-bit, I'd prefer moving away from treating it as an integer to a boolean on the API side.

**Comment by rianquinn** [comment]
@brendank310 What about the "automatically enabling the secondary controls"? Also... @RicoAntonioFelix what's your thought?

**Comment by brendank310** [comment]
I'm not a huge fan of automatic behavior in general. In my experience, it tends to lead to hard to track down bugs that come from an assumption of how the defaults operate. It's not always necessarily a issue with a developer not taking the time to investigate the automatic behavior either, they might not be aware that there was a choice to be made. Leaving things explicit avoids this class of bugs.

Side note, this is why I'm not very enthused about the 'every type is auto' approach, although so far I think the project has managed to use auto in appropriate places.

**Comment by RicoAntonioFelix** [comment]
I'm in favor of having things explicit, avoiding assumptions...

**Comment by rianquinn** [comment]
@connojd has this been merged yet? I want to say that is has, but I would like you to double check and close.

**Comment by connojd** [comment]
Yep this was in #272
