### ISSUE TITLE
Nested KVM/Xen support

### ISSUE THREAD

**Issue by jbremer** [Bareflank/hypervisor#268]
I briefly discussed using Bareflank in combination with KVM or Xen with Jacob, but wanted to raise the issue here as well, as I don't recall the exact specifics.

* Is it feasible to use a nested hypervisor to use Bareflank in combination with KVM or Xen?
* If extra development is required, would you have any rough ETA?
* What is the overall consensus on such a use-case?

**Comment by rianquinn** [comment]
@jbremer Are you looking to run Bareflank inside Xen / KVM? If so, that should work now assuming their nested virtualization support works properly. I do all of my development in VMWare, so it does work really well in the nested case. 

If your trying to run Xen / KVM inside of Bareflank, that's a ways out (likely June 2017). Please see [here](https://github.com/Bareflank/hypervisor/issues/231) for more information.

**Comment by jbremer** [comment]
Thanks. Please correct me if I say something incorrect/stupid ;-)

To simplify my question; I'm currently looking if I can use Bareflank+LibVMI in a KVM environment, therefore featuring the same (or more) functionality when compared to LibVMI's Xen support. With Bareflank+LibVMI I'd be interested to do introspection, memory events, etc on KVM virtual machines - much like LibVMI does for Xen (for not-dom0 VMs).

From what I understood Bareflank is almost capable of fully supporting libvmi.

**Comment by rianquinn** [comment]
Technically speaking you should be able to use LibVMI to introspect on a KVM/Xen VM without the need for nested virtualization, and that is supported today. @tklengyel

Now.. that being said, if you're interested in using Bareflank to support additional introspection above and beyond what LibVMI can do (which there is a pretty decent amount of things that you can do with a hypervisor that introspection cannot / should not do), that's a different story. 

Right now, LibVMI requires the ability to pause / resume the VM being introspected. Since Bareflank only supports the Host OS at the moment (guest support via a new Hyperkernel repo is in the works), pausing / resuming is not supported (as that would just freeze your machine 😄 ). Once we have guest support, adding LibVMI support should be possible, and we hope to have support for that sometime early next year. How we provide support for that is still in question (would love to see this added to [IncludeOS](https://github.com/hioa-cs/IncludeOS/issues/901) but this isn't something I have time for at the moment as my main focus has to stay on getting Bareflank more feature complete). @alfred-bratterud @RicoAntonioFelix 

If IncludeOS provides support for LibVMI sometime in the future (or someone works on adding support in their own fork), getting this to work should be pretty simple from a Bareflank perspective as it's just a matter of getting guest support up and running which is already planned, getting IncludeOS to work as a guest, which is already planned, and then finally making sure we have the proper hypercalls to support LibVMI which should not be that big of a deal once the [ExtendedAPIs](https://github.com/Bareflank/extended_apis) is near completion. 

So the short answer is, likely this should work one way or another early next year. Would love any help you can / are willing to provide.

**Comment by jbremer** [comment]
Thank you for the elaborate answer. Yes, LibVMI with Xen is excellent as-is, but LibVMI's KVM support is very limited - hence (part of) my question(s).
Lots of cool stuff upcoming, I'm looking forward to it. Don't expect much from my side, though, I'd be more of a Bareflank user rather than a core developer - I'll be staying in the loop and putting out more requests when the time is right :-)

**Comment by rianquinn** [comment]
Sounds great!!!

And feature requests are always welcome (actually needed is the better word), so if there is anything you want to see, feel free to toss in a feature request. The more information we know about what you need and what your use case is, the more likely we will be able to squeeze in what you need. 

Thanks a ton for the input, and I look forward to hearing from you in the future

**Comment by tklengyel** [comment]
@rianquinn: pausing/resuming the entire VM is not strictly necessary for LibVMI. You can very well use most of the LibVMI API without ever doing that. If you do more then passive introspection then you will need to be able to pause the vCPU when a VMEXIT information is forwarded and gets processed. We do have some asynchronous events on Xen but I yet to find a use-case for them that's feasible beyond simple logging.

**Comment by rianquinn** [comment]
@tklengyel Awesome. I hope to have LibVMI support in something like IncludeOS, doing so would not only provide a cleaner means to using it, but if you wanted to use it on the Host OS, you could (the hypervisor's not really going to care if the requests come from the Host or a Guest). So either way, it's on our roadmap, but it's good to know that the Host side of things should work well depending on your use case.
