### ISSUE TITLE
ELF Loader utilizes non-standard C const behavior

### ISSUE THREAD

**Issue by brendank310** [Bareflank/hypervisor#3]
The ELF error values defined in elf_loader.h are defined as const integer types, and subsequently used within the elf loader (specifically switch-case statements). Relying on non-standard defined behavior is going to hurt portability.

See:
http://stackoverflow.com/a/25597551

**Comment by rianquinn** [comment]
Are they saying that "const int blah = xxx;" is non-standard "C". The reason for using the const expressions is so that we can be explicit about the types. Some of the types in the code use 16bit signed, while others go as high as 64bit unsigned. Doing that with #define and "enum" is almost impossible. Out of curiosity, are you having problems compiling the code?

**Comment by brendank310** [comment]
Fixed by:
https://github.com/Bareflank/hypervisor/pull/8
