### ISSUE TITLE
Can bareflank be used a bare metal hypervisor?

### ISSUE THREAD

**Issue by gogo9th** [Bareflank/hypervisor#443]
Hi experts!

I am a researcher who plans to build a tiny bare metal hypervisor that can run small customized ELF OS images that runs on a mini board like Raspberry Pi, but running on Intel x64 architecture. I read all presentation slides for Bareflank, but I'm not sure if Bareflank is a bare metal hypervisor. 

a) If yes, could I get some instruction or tutorial on how to run a Linux kernel on Bareflank on a raw x86 laptop? 

b) If not, would it be possible to modify XEN to run on a small memory footprint such as 10~50MB?

Ronny

**Comment by rianquinn** [comment]
@gogo9th sorry it took so long to get back to you. 

Currently Bareflank does not boot from UEFI or coreboot, but @connojd is working on that support in the next month or two (unless someone else wants to do it first, help is always wanted). Bareflank is designed to support both type 1 and type 2 models. Currently we support most Intel 64bit hardware, including the minnowboard:
https://github.com/Bareflank/hypervisor/pull/409

As for running small ELF OS's in a guest, I am currently working on support for that this year. You can see our really, really simple support for this here:
https://github.com/Bareflank/hyperkernel

Our goal is to have basic vmapps, IncludeOS, and modified Linux kernels running by the end of the year, and this is our main use case for Bareflank's hyperkernel (i.e. we don't want to be another Xen / KVM, but instead provide support for research outside of what these hypervisors already provide). 

If you want to use Xen / KVM, and your interested in a small OS, take a look at IncludeOS.

**Comment by gogo9th** [comment]
Hi,

Thanks a lot for your reply. I was gladly surprised that Bareflank already runs on Minnowboard :) I think working and developing on Bareflank would be more desirable than XEN/KVM.

You said Bareflank currently doesn't boot from UEFI yet, but still can be run as a type-1 hypervisor. Then what currently loads Bareflank? (BIOS instead of UEFI?) And does booting type-1 Bareflank require any intermediate bootloader such as GRUB2?
 
Also, IncludeOS is a 32-bit binary. Can Bareflank run both 32-bit and 64-bit guest OS seamlessly on a x86_64 CPU architecture?

**Comment by rianquinn** [comment]
Bareflank is **designed** to run as a type-1, but doesn't do that yet. UEFI will be our first attempt at it, with coreboot after that (hopefully some of the code is shared, like the multi-core start routines). Bareflank always places the host OS in a VM when it starts which is a lot different than your typical type-2 which only places guest VMs in a VM. For this reason, Bareflank doesn't really care what host OS is running when it starts, could be Windows, Linux, UEFI, etc... We have encapsulated the startup routines in the bfdriver code:
https://github.com/Bareflank/hypervisor/tree/master/bfdrivers

All that is needed is for someone to implement the platform.c for the bfdriver for whatever OS is needed (I consider UEFI and coreboot an OS). One big difference with what we plan to do with UEFI vs what is there today is BFM is used to IOCTL to the bfdriver to load each ELF module and start the hypervisor. Instead, the UEFI code will simply read (or already have embedded) the hypervisor modules, and start when the UEFI driver starts since there is no need for an IOCTL interface on boot. 

As for IncludeOS, they are currently working on 64bit support as we speak. The hyperkernel can only start basic C/C++ applications as we have not finished our PV interfaces yet. Currently I am working on a new build system based on CMake, as well as a new memory manager that gets rid of some fragmentation issues we have seen. Once that is done, my focus will be on the PV interfaces that will be needed for IncludeOS and Linux. The code that is there now only supports 64bit, but there is no reason why it could not support both 32bit and 64bit.

**Comment by gogo9th** [comment]
I really appreciate that you guys are putting much effort on developing an open-source hypervisor. Bareflank will become Linux in the field of hypervisor. I wish I could help, but I originally don't have much background in systems programming. I have some basic experience in modifying and recompiling Linux kernel to add TPM support on it (similar to Linux-IMA), but don't have any experience in hypervisor. In any case, if I want to use Bareflank in the future, I should get familiar with its current source code, anyway. I also really hope we finally get type-1 Bareflank booting from UEFI and running small real OSes.

**Comment by gogo9th** [comment]
Another nice OS to run with Blareflank is Zephyr (https://www.zephyrproject.org/). Zephyr OS image is 32-bit, but as you said there'll be no reason it can't run on Bareflank.

**Comment by rianquinn** [comment]
@gogo9th Agreed, that would be another goos OS to run someday. I'm going to close this ticket for now. Let me know if you need anything else.
