### ISSUE TITLE
Support for distributed Hypervisor

### ISSUE THREAD

**Issue by ohault** [Bareflank/hypervisor#476]
The idea would be to create a network abstraction to support the concept of a distributed Hypervisor.

This includes Distributed Memory Manager and mapping of remote ressources like CPU core as vCPU

The architecture should be network agnostic (PCI Express interconnect, Infiniband, 10/40/100G Ethernet,..)

**Comment by rianquinn** [comment]
Thanks a ton for the interest in the project. 

Bareflank is just the scaffolding to create new and exciting hypervisors; it's not a full blown hypervisor like Xen or KVM. In other words, Bareflank's mission is to provide an easy environment so that other people can create the hypervisor you're describing.
