### ISSUE TITLE
[RFC] bfvmm: minor serial refactor to support ARM

### ISSUE THREAD

**Issue by cpavlina** [Bareflank/hypervisor#507]
# Description

Most ARM devices we're targeting have a serial peripheral of the same type as the existing x64 one. As such, adding support for this should be fairly trivial. I'm proposing a few changes to cleanly separate the differences between platforms in the serial code.

# Proposed changes

- Rename `serial_port_intel_x64.*` to `serial_port_ns16550a.*`. Names for this class of serial peripheral vary (many vendors have made chips with similar behavior) but this is the name the Linux kernel uses for it.
- Possibly temporary: place architecture `ifdef` guards around `DEFAULT_COM_PORT` in `bfconstants.h` because those are not the same on ARM.
- Implement the `portio` intrinsics for ARM (which are just MMIO there, but the existing abstraction seems acceptable to me).

# Possible future changes

We may want to look towards adding a build option to specify the base address, because it's much less predictable on ARM. Alternatively, we may consider having `bfdriver` locate this from in the Linux kernel context and pass it in at runtime (it's in the device tree). A sane value for `DEFAULT_COM_PORT` for now would probably be the base address used by the QEMU configuration we're currently using.

**Comment by rianquinn** [comment]
Current the build option already exists. If you look at the #define guards, they allow you to define during compilation what you want. So for example, `"CXX_FLAGS="-DDEFAULT_COM_PORT=0xE000" make` should work. 

Is it possible to use MMIO instead of portio for both x64 and ARM? If so I would love to see the code cleaned up so that it uses MMIO for everything. I have also always hated having this in the public interface:
https://github.com/Bareflank/hypervisor/blob/dev/bfvmm/include/serial/serial_port_intel_x64.h#L55

I'd love to find a way to get this into the private interface while still being able to support testing in a clean way.

**Comment by cpavlina** [comment]
I have no idea if using MMIO for this on x64 is possible, you'll have to ask someone more familiar with the platform. I'd tag someone but I'm not sure who.

I feel like a build option to define the port is something we should have as a cmake option so it's more discoverable.

**Comment by rianquinn** [comment]
@ktemkin? @brendank310?

**Comment by cpavlina** [comment]
@ktemkin and I briefly discussed this; I'm not positive I fully understand what's going on (x64 is still pretty unfamiliar to me) but it sounds like serial peripherals via MMIO may not be reliably listed in the ACPI tables? Looks like portio may still be the most reliable approach there.

**Comment by ktemkin** [comment]
Looks like only a subset of x86_64 actually surface MMIO windows to their NS16550 correctly via ACPI, so it looks like PIO is still the way to go on x86.

**Comment by rianquinn** [comment]
This has been completed
