### ISSUE TITLE
if the app is compiled with debug symbols

### ISSUE THREAD

**Issue by kunlilin2991** [Bareflank/hypervisor#516]
I wonder if the hypervisor is compiled with debug message? 

I am new in kernel program, when I use gdb to `add-auto-safe-file-path bareflank.ko 0x`. gdb tells me that there is no symbols found. and I use `file bareflank.ko` , the output message is ` not stripped` 

if the app is compiled with debug message, and how to change it? 
thanks very much.
Besides, if there any docs for debug the hypervisor?

**Comment by rianquinn** [comment]
Right now, debugging the hypervisor is done using serial, the debug ring via `make dump`, as well as your typical JTAG debugging. Debug symbols are not going to be available inside the kernel because the hypervisor is compiled as a set of ELF modules and loaded as a separate binary. I talk about the whole process here: https://www.youtube.com/watch?v=uQSQy-7lveQ

**Comment by kunlilin2991** [comment]
thanks so much, and I wonder how i can get the symbol tables to debug this excellent hypervisor?
Besides, I use gdb to connect gdb server in qemu virtual machine, does this means works or not for debugging the hypervisor?

**Comment by rianquinn** [comment]
That likely will not work. You can get the debug symbols the same way you would any Linux .so or main executable (i.e. via ELF).

**Comment by kunlilin2991** [comment]
what is the differences between branch master and dev.  and what is the reason why the dev hypervisor should be compiled with cmake 3.6 or up version? I modify the `cmakelists.txt` to be cmake 3.5`. in the process of compiling, I receive the following message
```markdown
CMake Error at tmp/json-gitclone.cmake:49 (message):
  Failed to checkout tag: 'v1.2'

CMakeFiles/newlib.dir/build.make:89: recipe for target 'external/newlib/stamp/newlib-download' failed
make[2]: *** [external/newlib/stamp/newlib-download] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/newlib.dir/all' failed
make[1]: *** [CMakeFiles/newlib.dir/all] Error 2
```
Is that is bug or not?

**Comment by rianquinn** [comment]
We use GIT_SHALLOW which is a 3.6 feature which is why you are having the compilation error. You could remove those and I think you would end up only needing 3.2, but I have not tested that at all. Dev is our "v1.2" build which will be merged into master once our build system has stabilized. There are still changes being made to support ARM.

**Comment by rianquinn** [comment]
Closing for now, let me know if you have any more issues.
