### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by bronzeMe** [Bareflank/hypervisor#517]
hi,when I compiled the project by executing 'make',it occured errors as following,could someone give tips?Thanks.
------
test@test~/Downloads/hypervisor-1.1.0$ make
--> /home/test/Downloads/hypervisor-1.1.0/makefiles/bfc
SYSROOT_NAME=vmm /home/test/Downloads/hypervisor-1.1.0/build_scripts/build_newlib.sh
~/Downloads/hypervisor-1.1.0 ~/Downloads/hypervisor-1.1.0/makefiles/bfc
Fetching newlib. Please wait...
Cloning into 'source_newlib'...
remote: Counting objects: 6216, done.
remote: Compressing objects: 100% (3971/3971), done.
remote: Total 6216 (delta 2178), reused 6140 (delta 2173), pack-reused 0
Receiving objects: 100% (6216/6216), 11.19 MiB | 144.00 KiB/s, done.
Resolving deltas: 100% (2178/2178), done.
Checking connectivity... done.
~/Downloads/hypervisor-1.1.0/makefiles/bfc
~/Downloads/hypervisor-1.1.0/build_newlib ~/Downloads/hypervisor-1.1.0/makefiles/bfc
Building newlib. Please wait...
make[3]: *** [/home/test/Downloads/hypervisor-1.1.0/sysroot_vmm/x86_64-vmm-elf/lib/libc.so] Error 77
make[2]: *** [build_src] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by rianquinn** [comment]
What are you compiling on? What were your build steps (you have to run more than make to get a complete build)?

**Comment by bronzeMe** [comment]
operation system Ubuntu14.04 ,gcc version 4.8.4, compiled the project as following : 
1./tools/scripts/setup_ubuntu.sh,this step was successful.
2.make ,some errors occured as above commited discription.

**Comment by rianquinn** [comment]
Is this 64bit?

**Comment by rianquinn** [comment]
Also, have you tried compiling using the dev branch? You might have better luck with that. THe instructions are in the README for the dev branch

**Comment by bronzeMe** [comment]
Yes,it's 64 bit OS,then I tried 'git checkout -b v.1.2.0 ',but when 'make' the project it occured errors as before.

**Comment by rianquinn** [comment]
So a couple of things:
- GCC 4.8 is not supported as we use a lot of C++14, so if you are using Ubuntu 14.04, you have to update the system to use the latest and greatest GCC. The instructions for how to update the system can be seen in our Travis CI script.
- The setup script should have failed because 14.04 is not a supported platform. It works, but like I said above you have to do a lot to get it to work because 14.04 is so out-of-date. You can see the supported versions of the script here: https://github.com/Bareflank/hypervisor/blob/master/tools/scripts/setup_ubuntu.sh#L57
- There is no v1.2.0 tag yet, so that checkout should have failed as well. If you want to use the new build system, you need to checkout the "dev" branch, but keep in mind, you still have to update our 14.04 system with the latest tools. Once again, the Travis CI script will show you how to do that. 

If you can, you should use a supported version of Ubuntu which is 16.10 and up.

**Comment by bronzeMe** [comment]
Thank you so much!!!,I compiled and run the project successfully on Ubuntu 17.04 64 bit~~

**Comment by rianquinn** [comment]
No problem. Let us know if you run into any issues.
