### ISSUE TITLE
[RFC] High-level naming and directory structure

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#529]
**Directory names**
This RFC is intended to start a discussion about the high-level component names used by the Bareflank hypervisor. The bulk of the hypervisor code resides under the bfvmm directory:

- bfvmm/src
  - debug_ring
  - exit_handler
  - intrinsics
  - memory_manager
  - serial
  - support
  - vcpu
  - vcpu_factory
  - vmcs
  - vmxon

The last two - vmcs and vmxon - are the only names that assume an architecture. I propose that we create a new directory called `vmctl` (short for virtual machine control), and place the vmcs/vmxon code under an x86-specific directory. Something like

- bfvmm/src/vmctl
  - arch-independent vmctl files
  - arch/
    - x86/
      - intel/
        - vmcs files
        - vmxon files
      - amd/
        - vmcb files
    - aarch64/

I decided on `vmctl` because I think that it conceptually captures what the vmcs and vmxon currently do. This directory will be the location of the state needed to manage virtual machines. A "virtual machine" is any code that runs at a less-privileged level than the VMM. The VMM is code that runs with hypervisor privileges. So on ARM, the VMM will run in normal world at EL2, and will manage code that runs in normal world at EL1 and EL0 (i.e. VMs). In Intel-speak, the VMM runs in VMX-root and a VM is any code that runs in VMX-nonroot.

If we go this route, it will probably make sense to mirror the above layout for each of the bfvmm's high-level modules. So the bfvmm would look like

- bfvmm/src/\<module\>
  - arch-independent files at the top level
  - arch/
    - x86/
      - intel/
      - amd/
      - ...
    - aarch64/
      - ...

where \<module\> = debug_ring, exit_handler, memory_manager, etc.

**Other Issues**
- Right now the build system treats each child directory under bfvmm/src as a module.  Without any changes to the build system, the proposed directory change would create one "vmctl" module and would effectively decrease the modularity from before. With changes that @JaredWright is making to the build system now, I think this will be relatively simple to address though.

- The intrinsics directory is by far the largest directory under bfvmm. Most of the code is under include/intrinsics and it already follows a structure similar to the proposed one above. Conceptually, the intrinsics code is the software layer that interacts directly with the hardware. One issue that I have with its current location is that the code is not specific to the bfvmm, as it is also used by the [extended_apis](https://github.com/Bareflank/extended_apis) and the [hyperkernel](https://github.com/Bareflank/hyperkernel), and really it could be used by *any* code that needs to interact with the hardware in some way.  I think that moving the intrinsics code to the top-level would help illustrate the role that the code actually plays

**Comment by JaredWright** [comment]
I like the proposed directory name and structure for bfvmm/src/vmctl. I also like that idea as the go to directory structure for every component that contains both architecture-agnostic and architecture-specific code. For components that don't have any architecture specific code, this directory structure can still be followed by just omitting the /arch subdirectory.

An alternate solution might be to keep the current vmcs and vmxon directories structured as they currently are, but rename them to "vmstate" and "vmminit". vmstate will contain all code that represents a vm's state, and vmminit will contain all code used for initializing (turning on) the vmm.

Comments about the "Issues" section above:

1) The new build system should be flexible enough to support any rearranging of directories that we want to do

2) I really like the idea of moving the intrinsics code out of the vmm directory into it's own directory one level up (to /hypervisor). I like this idea because the intrinsics code really is a separate software layer than the vmm code: the vmm code **uses** the intrinsics as an API to control hardware. In the context of Bareflank, I think the current "intrinsics" directory contains what I usually refer to a **hardware abstraction layer**, or hal for short. Further, the word "intrinsics" is a word that leads me to think about x86 (i.e. AVX, SSE, etc) or ARM (NEON, etc) intrinsic functions/features. With all of that in mind, I think it would be good to create a new directory /hypervisor/hal, and start migrating the current intrinsics components there.

**Comment by rianquinn** [comment]
Besides maybe the gdt/idt (which can be moved to the VMM and out of the intrinsics since it doesn't make much sense in it's currently location), the bulk of the intrinsics code really is "intrinsics". A good example is the following:
https://github.com/Bareflank/hypervisor/blob/dev/bfvmm/include/intrinsics/x86/common/pm_x64.h

Things like CPUID, VMCS, MSRS CRS, etc... all take on the same form as above with the only added code bing bit manipulations on the read / written values to simplify working with these instructions (very similar to what Linux does). 

Now that being said, I am a fan of getting that code out of the VMM as it could be used by more than just the VMM. I'd love to rename the SDK (since it's not that anymore), and put the intrinsics in with the other includes as we already have the vmcall intrinsics in there.

**Comment by JaredWright** [comment]
@rianquinn I am thinking of "intrinsics" in this context:
https://stackoverflow.com/a/2268599
https://en.wikipedia.org/wiki/Intrinsic_function
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#

… in other words, I think of an intrinsic as something that a compiler replaces with inline instructions instead of a function call. I'm thinking of things like halt() and stop() (and the other examples you mentioned) as something different: functions that belong to a hardware control library/API.

Granted, I'm not super familiar with the intrinsics directory yet, but at a first glance, it appears that most of the stuff in their belongs to the later category. It is all linked together into the bfvmm_intrinsics library, right? Or am I missing something, and those functions somehow get inlined into the VMM modules by the compiler?

Also, the stuff that is currently in the bfsdk directory seems like a distinct layer from the stuff that is in intrinsics. At a glance (again, I'm not super familiar yet), bfsdk seem to revolve around defining interactions between VMM software components, rather than between the VMM and hardware.

**Comment by JaredWright** [comment]
Hmm... after looking a little closer at the headers in bfvmm/include/intrinsics, it looks like it does work a little different than I thought. Those really are being used as intrinsic functions that are being inlined when VMM components use them. Is that correct?

**Comment by rianquinn** [comment]
yeah, we simply implement them in NASM because GAS is horrible. Intrinsics are not always inlined BTW (although they usually are). But yeah, they are intended to be just like the Intel intrinsics you listed in the previous post, with the only real difference being that we provide the bit manipulations for the intrinsics that manage bit fields, and we also provide some additional logic for intrinsics that return error codes in RFLAGs (as there is no simple way to convert them to C or C++). 

The only thing that is in there that really doesn't make sense is the IDT / GDT source code, which probably needs to find a home in the VMCS module

**Comment by cpavlina** [comment]
FYI - I'm going to start implementing some of this locally as I need this structure at this point to properly implement aarch64. I'll continue to track this RFC and modify my implementation to match if this RFC changes at all - with @JaredWright's new build system this should be flexible enough to do that easily. At this point I have no additional input, the structure as is looks good to me. One minor change I do plan to make is renaming `x86` to `x86_64` as that is the name currently used by the build system to identify that target; we can also use `x64` (just speak up if you prefer that) but `x86` is 32-bit :P

**Comment by JaredWright** [comment]
I created another sandbox repository to continue the discussion on this RFC: https://github.com/JaredWright/bfdir_structure_sandbox. 

That repo is my attempt to convey personal vision of what the 'end goal' for the source tree would look like after restructuring. Thoughts @rianquinn @connojd @cpavlina? Too much for this RFC? Any small bits and peices that people like?

**Comment by cpavlina** [comment]
I'm a bit disengaged right now so I don't have much to say but I will comment on two things:

- I like moving intrinsics out of bfvmm.
- I'm skeptical of removing the bf- prefix. It's used pretty thoroughly in the project and removing it here would add inconsistency. Case in point:

> This is bfm, but sense I'm suggesting getting rid of the "bf" prefix on all the top level directories, I don't think we could really have a directory just called "m"

The executable compiled from these sources is actually called `bfm`, and we can hardly call it `manager` as the name of the executable shouldn't be so generic when it could be installed somewhere like `/usr/local/bin` by a user.

**Comment by rianquinn** [comment]
My notes:
- I like the intriniscs being moved outside of the VMM as that would remove some duplication. 
- Use of hpp I am not a fan of, and it's not really a supported naming scheme for C++ (there are many discussions on the core guidelines about this)
- I am fine with respect to removing the "bf" from the folders (thats an old carry over from 1.0), but some things still need it like "bfelf_loader.h" and BFM. We don't want "m" in /bin, and we cannot use "elf_loader.h" as it will interfere with the existing ELF loader headers in Linux. 
- I don't like the vmm_xxx folders. The current SDK headers are used by all of Bareflank and it's extensions, not just the VMM. The bfsysroot (which I agree needs to be renamed for sure), is used by not only the VMM but also guests in the hyperkernel so it's not a VMM specific thing, and the extensions folder I am not a fan of as I prefer the extensions being in their own repo as we want the hypervisor repo to be as small as possible, otherwise I think it would lead to confusion and be a bit overwhelming. 
- Also you missing the driver logic (or did I miss that)

**Comment by cpavlina** [comment]
> I am fine with respect to removing the "bf" from the folders (thats an old carry over from 1.0), but some things still need it like "bfelf_loader.h" and BFM. We don't want "m" in /bin, and we cannot use "elf_loader.h" as it will interfere with the existing ELF loader headers in Linux.

I feel like we're risking introducing a lot of confusing inconsistency by only using bf- when necessary to avoid naming collisions. It doesn't make much sense to me to "randomly" have some things namespaced and others just lying around in the global space because they happen not to collide with anything. Either remove it from everything (not feasible) or from nothing, IMO...

**Comment by rianquinn** [comment]
To be honest, I'm actually cool either way on this specific topic as I see it both ways so likely it just makes sense to leave the part alone

**Comment by rianquinn** [comment]
@connojd @brendank310 @RicoAntonioFelix @josephsharkey Any comments?

**Comment by connojd** [comment]
+1

**Comment by rianquinn** [comment]
@connojd / @JaredWright Please review and let me know if we have covered this. I believe we have, but I want a double check first

**Comment by JaredWright** [comment]
I think this RFC is pretty stale and irrelevant given the recent build system updates. I don't see any reason to keep it open

**Comment by rianquinn** [comment]
Fixed: https://github.com/Bareflank/hypervisor/pull/575
