### ISSUE TITLE
[RFC] Merging aarch64 support

### ISSUE THREAD

**Issue by cpavlina** [Bareflank/hypervisor#608]
There are still several outstanding issues before aarch64 support can be merged; I'm opening this RFC to discuss how we should go about it. The issues I see are as follows:

1. Unwinder is still broken. Jared has suggested merging anyway so that I'm not still sitting on a pile of ARM stuff and other people can poke around with it, pointing out that several other things obviously aren't ready either (e.g. testing) and we've already decided we're okay with that.
1. Due to the lack of ARM intrinsics and related code, sections of `bfvmm/src/entry/entry.cpp` have to be blocked with `#ifdef`. This also means vmcall (hvc) has been stubbed out temporarily as we have nothing in place to handle it.
1. As mentioned, no testing yet, other than pieces of code already hit by x64 tests.
1. Handful of minor bugs I'll open issues for shortly. #609

What do we make of this?

**Comment by JaredWright** [comment]
1. I agree that merging the (almost working) aarch64 unwinder is a good idea, so that other people can poke around at it. I usually wouldn't be excited to merge broken code, but this component is such a fundamental (and complex) piece of the runtime environment that I think incremental development is ok. I don't think we will be able to proceed any further until it is working extremely well anyways, so I don't foresee the unwinder just sitting around in broken status for very long. 

2. Are the ```#ifdef```s you're adding throughout the source code to exclude components that aren't yet developed for aarch64? I'd be a little hesitant if thats the case, but I'd have to see what you were planning to ifdef out first.

3. I don't see any issues with no testing being there yet for aarch64, because at this point in time we are only working on runtime environment components (which are almost dependencies) and not hypervisor components.

**Comment by cpavlina** [comment]
https://github.com/cpavlina/hypervisor/blob/aarch64-hack-new/bfvmm/src/entry/entry.cpp#L66

Not a big fan of that but I'm not sure how else to handle it for now.

**Comment by rianquinn** [comment]
1: Agreed
2: With my current version branch, the vcpu issue will not be a problem because the default vcpu doesn't do anything, so these #defines should not be needed. 
3: That's fine. Add the folders that are not tested to the codecov.yml to exclude them from testing for now.

**Comment by rianquinn** [comment]
Here is the branch:
https://github.com/rianquinn/hypervisor/tree/rfc_602

**Comment by rianquinn** [comment]
Closing for now.
