### ISSUE TITLE
[RFC] Intel virtual interrupt controller (VIC)

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#649]
**Overview**
The virtual interrupt controller (VIC) provides interrupt services to clients, in addition to managing physical and virtual interrupts. Specifically, the [current version](https://github.com/connojd/extended_apis/tree/vic) provides functionality to
* Register interrupt handlers for a given vector
* Remap physical vectors to virtual vectors
* Convert physical vectors to virtual vectors and vice versa
* Send physical inter-processor interrupts (IPIs)
* Inject virtual IPIs

**Notes on current implementation**
* Much room for optimization
* Only physical and virtual x2APIC supported (xAPIC will be supported once @JaredWright has the EPT code merged)
* External interrupt exiting is enabled on construction of the vic
* Uses identity map for interrupt pass-through
* Some implementation details leak through the public API e.g. the various handle_x2apic* exit handlers are in the public interface, but aren't really meant to be called external to the vic. If this is an issue, we could make the bfvmm's exit_handler a friend of the vic so that we could register private exit handlers. That would help to de-clutter the current public interface

**Questions**
1. Are there any additions or deletions you think are needed for the API?
2. What should the nature of the vector mapping be? Do we need to support multiple phys to one virt? Or multiple virt to one phys? Neither? Both? Right now users could potentially map multiple phys vectors to one virt

**Comment by rianquinn** [comment]
Any mention of an APIC should be in an arch/intel_x64 folder as this is at a minimum, x86 specific.:
https://github.com/Bareflank/extended_apis/blob/master/bfvmm/include/vic/arch/intel_x64/virt_x2apic.h

In general, if you have to include something from the arch folder, you should also be in an arch folder.

**Comment by rianquinn** [comment]
Comments:

- [Here](https://github.com/Bareflank/extended_apis/blob/master/bfvmm/include/vic/arch/intel_x64/virt_x2apic.h#L62):
Since you are inheriting the lapic class, this should be marked override, or final

- [Here](https://github.com/Bareflank/extended_apis/blob/master/bfvmm/src/vic/arch/intel_x64/phys_x2apic.cpp#L40):
Is there a need for const? Fix all

- [Here](https://github.com/Bareflank/extended_apis/blob/master/bfvmm/src/vic/arch/intel_x64/virt_x2apic.cpp#L158):
If you are calling a function that is internal to a class, use "this->". Fix all

Question: Are external interrupts disabled in the VMM? The only interrupts that should fire in the VMM are exceptions. All other interrupts should be disabled in the VMM using CR8. 

In general, I am very impressed with this implementation. Clean code, well thought out. Great Job!!! My only closing comment is, should this code just be moved to HVE since it is all Intel specific?

**Comment by connojd** [comment]
1. Will mark as final
2. I like to help the compiler as much as possible, and it also makes the intent more explicit; if you don't intend on changing the value, IMO it should be marked const. See [here](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rconst-const).
3. Will add 'this->'

 A1: Interrupts are disabled in the VMM via rflags. Using CR8 disables them in the guest as well (as the code stands; we could add cr8 to the save state if we wanted to but I don't see the advantage).

A2: There is certainly an argument for moving it to HVE, even though the APIC itself has nothing to do with virtualization. Another issue is that there will alot more code added in the future(xAPIC, IOAPIC, VT-d) and putting it all into HVE will cause a corresponding swell in the HVE code. That being said, things like VT-d support certainly are hardware virtualization extensions, so I don't really know the best answer

**Comment by rianquinn** [comment]
2: That's fine
A1: If external interrupts are enabled in the VMM, every interrupt causes a world switch, and a context switch, and context switches are not highly optimized in the VMM at the moment, so they should be avoided. We really need to highly optimize the interrupt path as latency here really has a huge impact on performance. To prevent CR8 from being disabled in the guest, create a shadow TPR that is saved / restored on enter / exit (i.e. disable external interrupts prior to enabling interrupts in the VMM and vice versa), and then use the CR8 handler to update the TPR shadow. 
A2: I think for now, it makes more sense for this code to the in the HVE since I think that is were people are going to look for it. I'm less concerned about the size of the HVE module as modules are there more to allow people to swap out certain functions, and less about organization.

**Comment by connojd** [comment]
Are you saying you want interrupts enabled in the VMM, or disabled? The code disables them now

**Comment by rianquinn** [comment]
External interrupts disabled in the VMM, exceptions enabled.

**Comment by connojd** [comment]
Thats what is happening now. You can never disable exceptions, and the interrupt isn't delivered through the VMM's IDT; the vector is taken from the vmcs, so there is "only" a world switch.

**Comment by rianquinn** [comment]
Ah.... ok, that's what I was looking for. Awesome.

**Comment by connojd** [comment]
However, it would be interesting to measure the performance of enabling them, because if you could receive interrupts while in the VMM, that would mean those interrupts only cause a context switch rather than a world switch, at the expense of (greatly) complicating the VMM's code

**Comment by rianquinn** [comment]
Agreed. A great task for later I think, but one that should be done.

**Comment by rianquinn** [comment]
@connojd How are we doing on this task?
