### ISSUE TITLE
Different output between in host linux and qemu guest linux

### ISSUE THREAD

**Issue by kunlilin2991** [Bareflank/hypervisor#698]
I use the version v1.1.0 to develop a program, but, the output goes different between the two system. 
and for your example, in QEMU with ubuntu16.04, it would change rip to hooked hello world. but, the output would be right in host linux. 
I develop a new project, setting some trap on some ept entry, The results go right with QEMU ubuntu, 
but in linux, no trap seems to be work. 
I just confused with that result......

**Comment by rianquinn** [comment]
yeah, that's interesting. I will say that the hook example might not work on every system. The RIP trick is a hack to make that work. Our goal was to keep the example as simple as possible. The better approach would be to use capstone to disassemble the instructions to perform the hook.

**Comment by rianquinn** [comment]
When I get a chance, I will see if I can repro this. I really wish we had the hook example ported to the new implementation of EPT as that would make things a lot easier

**Comment by kunlilin2991** [comment]
In addition to the given example, I used the project to test my own code ,I set the traps on some ept entries, similarly, in QEMU , it works and cause VM Exit, but on host Linux, no traps work.......  for example, in my test, I first find the address of sys_call_table, and then set the ept entry without read permission, in exception handling, an vector event(double fault ) is injected to the VM, in QEMU, these tests are normal, but on host Linux these are not executed.....

**Comment by Randshot** [comment]
I always let the userspace application do the hooking/patching, since I had no way to do this in the HV.
@rianquinn Now my question is whether it is possible to load hooking libraries such as minhook into the VMM. I am asking since capstone was added as a dependency for eapis.

**Comment by rianquinn** [comment]
@Randshot Capstone was added because more often than not, you need a disassembler for x86, even for simple things that are not RE/Introspection related. 

Technically, you can add any library you want to the VMM so long as you can get it to properly link. Since we use our own ELF loader, anything is possible really, just depends on how much cross-compiling you will have to do. For example, last year I got LibVMI to compile in one of our C++ VMs for the hyperkernel while I was playing around with that code, but I had to cross-compile glib, which was not easy as it had a lot of dependencies. If you want to pull a library in, you can, but if it has a ton of dependencies other than C it might prove to be really difficult.

Oh, and hooking can definitely be done from the VMM and is used a lot for RE/Introspection use-cases. The hook example that we provide is just that... and example. It's not meant to be a complete working solution. Once again, our goal with Bareflank is to provide an SDK and not a hypervisor that does everything out of the box without work from the user.

**Comment by rianquinn** [comment]
This should be addressed with the new example. Let me know if you're still having an issue
