### ISSUE TITLE
[QUESTION] Memory protection between VMs

### ISSUE THREAD

**Issue by krystian-hebel** [Bareflank/hypervisor#736]
Following our previous research we discovered that UEFI is even less MP-friendly than we expected. As in our project multiple UEFI applications (each of them most likely uses UEFI services) will run simultaneously and most of UEFI API is neither reentrant nor MP-safe we need to walk around this issue. I know this isn't exactly Bareflank issue, but perhaps someone had similar problem.

Right now we have 2 (2.5) ideas to address this:

1. Starting new instance of UEFI on each core separately
In this case each VM pretends to be 1-core system, which requires cpuid and MSR handlers. Every one of them gets a part of physical memory by using EPT, one per VM. Images of UEFI most likely need to be stripped from most of hardware initiation in this case (modified OVMF?). Still, these images take some space, both in flash (we're still planning to embed it if possible; most of OVMF is already compressed so not much can be gained here) and RAM (no code sharing between VMs). Some problems may appear if interprocessor communication will be required later.

2. Implementing COW (copy-on-write) with EPT violation handlers
UEFI environment that started Bareflank and became host-VM is reused. Some of RAM will be reserved for copies of pages. Initially all VM memory is marked read-execute in EPT, when VM tries to write one page is copied to reserved space, remapped in EPT and marked read-write-execute. This of course requires one set of EPT for each VM, instead of one global. Some of UEFI global structures are used for managing exclusive access to the hardware, by doing it this way we will lose that protection, so it will need to be moved to VMM. After that UEFI applications hopefully would be able to start from APs with MP Services.

- Variant of the above with modified CPU registers
APs in UEFI do not have interrupts enabled by default. It may be required to install handlers for some interrupts (most likely timer is used for some events). Easiest way to do this would be to copy BSP state to APs, so all cores would "return" to the same point, differentiated later (by e.g. cpuid) if necessary.

Are there other ways than mentioned? Which approach is most reliable / easiest to implement / have smallest overhead during setup / at runtime? Are there any possible issues with them that we missed?

**Comment by connojd** [comment]
@krystian-hebel which of the APIs are you talking about? The efi driver itself?

**Comment by krystian-hebel** [comment]
@connojd driver works as expected. I'm talking about UEFI Boot/Runtime services, protocols etc. Booting OVMF from UEFI is part of the first idea, but we didn't get as far just yet.

Our initial idea was to load (after was Bareflank started) 4 new UEFI applications, one per core, using UEFI MP services, but because it was designed as firmware it isn't expected to do such tasks. Everything seems to work fine when APs get simple functions to do, but platform hangs when it is told to use UEFI services to load application (LoadImage, StartImage) that can make use of UEFI as well. When BSP starts APs one at the time in blocking mode platform hangs much later, but still hangs.

By the specification APs should not be given tasks that require UEFI's support (other than basic memory management). We are hoping to overcome this with virtualization.

If this isn't proper place for such question please let me know.

**Comment by rianquinn** [comment]
Right... UEFI MP services is not a replacement for a symmetric kernel. It only executes one thing at a time. The MP services are designed so that you can install your own symmetric kernel linearly. 

IMO, that is what I would do. I would use the MP services to load code into each core and then execute from there. They wouldn't be UEFI applications as much as they would be applications that use your AP logic as well as the UEFI runtime services like an OS would. 

The approaches you have listed above would all probably work, but I think they would be harder to get working than to simply load your applications on to the APs that you want to run them on, and only use the UEFI runtime services as needed. In this case, all you would have to do is provide the init/sipi / 16->64 boot logic which in total would be like 100 lines of code. Its really simple. From there, your applications would use UEFI runtime services as needed as if they were UEFI applications.

**Comment by krystian-hebel** [comment]
That would be a good advice if we had control over applications. See, we were given just the binaries, so we can't just change them, neither disassembly them due to license issues to see what exactly they expect from UEFI. They at least use boot services to print to console, so they definitely need at least that, probably even more.

Thanks for the suggestion anyway.

**Comment by rianquinn** [comment]
@krystian-hebel Ah, ok that makes a lot more sense. In that case I would do 1. We actually got pretty close to doing exactly that, but you might have to include some additional stuff like changes to ACPI to make it work. Hooking UEFI might also help so that you can debug problems by watching which calls to UEFI are giving you issues.

**Comment by rianquinn** [comment]
Going to close this for now. If you have any more question, feel free to reach out.
