### ISSUE TITLE
[RFC] EPT flushing when sharing with IOMMU

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#877]
It is often convenient and natural to set a domain's EPT as the second-level page table referenced by an Intel IOMMU context entry. A drawback of doing this through is that if the IOMMU's page-table walk is not coherent with the CPUs, any EPT changes must be clflushed to ensure the IOMMU sees the correct data. Currently the ept::mmap code does not provide an API to do this.

Any thoughts on providing an API that can cater to this use case?

**Comment by JaredWright** [comment]
I sorta think this could be solved by supporting many implementations of ept::mmap, along with a way to apply a specific "mapper" to a vcpu based on your specific needs. If we did that, we could make a dedicated mmap implementation that flushes modified entries every time they are modified. We could also have implementations for mmap that optimized for other various other aspects as well (small memory usage, fast entry modification time, etc)

**Comment by rianquinn** [comment]
I like this idea. Specifically, I would suggest that Bareflank's implementation of the EPT mapper should be minimal (even more so that it currently is). If there is a way to swap out which EPT mapper is used, others can implement mappers that are more complex, and better suited for their needs, but the upstream project would not need this type of complexity.
