### ISSUE TITLE
Linux module restrictions

### ISSUE THREAD

**Issue by andyhhp** [Bareflank/hypervisor#894]
As a heads up, Linux is starting to restrict what it will let modules do:

https://lore.kernel.org/lkml/20200407110236.930134290@infradead.org/T/#u

and is likely to impact Bareflank.  This started to fix a bug with splitlock handling (on Tremont and IceLake, hypervisors need to fudge things to prevent the guest getting #AC when it wasn't expecting to see it), but has been extended to anything which modifies control/debug registers.  It is also liable to be extended to include further things.

**Comment by connojd** [comment]
@andyhhp thanks for heads up. I'm not familiar with splitlock handling, I wonder if there is a way to be sld_safe and still do VMX things?

**Comment by andyhhp** [comment]
Its a total mess.

In ~all x86 implementations, any locked operations

**Comment by connojd** [comment]
> KVM's approach was to emulate the instruction without its atomic properties.

That does not sound fun at all, considering the number of instructions that can be locked

> As I said, a total mess.

Just one thing after another for Intel these days. Do you know if AMD has a similar problem?

**Comment by andyhhp** [comment]
> Just one thing after another for Intel these days. Do you know if AMD has a similar problem?

Bus locks on this condition, yes.  Splitlock detection and #AC, no.

Also, if you see the most recent revision of Intel's ISA Extension manual https://software.intel.com/sites/default/files/managed/c5/15/architecture-instruction-set-extensions-programming-reference.pdf version 38, see Chapter 6 for a similar feature appearing to combat problems from lock on non-WB cached memory.

**Comment by connojd** [comment]
Now that is an exciting little document! Tertiary processor controls! I have some reading to do..

**Comment by rianquinn** [comment]
@andyhhp Thanks a ton for the heads up. My inbox is a total disaster and I am trying to catch up on everything, only to run into this. 

So, I tired to read through the whole thing. I'm not sure I understand exactly what is happening here, so let me know if I am on the right track:
- Linux is about to remove the ability to allocated executable pages
- Linux is about to remove the ability to read/write CR and DR registers. 

This would be HORRIBLE if that were true. Couple of questions?
- How exactly is Linux going to prevent you from touching CR/DR since Linux is monolithic? Right now we have our own assembly routines that manage these registers, which I am assuming they are trying to prevent. 
- I am assuming that is is only an issue for loading a hypervisor _after_ Linux boots. When we load before Linux, this should not be an issue. 
- Has there been any progress on this? I'd love to know more about what their proposed plans are for allocating executable memory and handling the VMX bits. 

Thanks again for reaching out. Super helpful.

**Comment by rianquinn** [comment]
I started to read through this a bit more to see if I could better understand the patch itself. It appears that they are attempting to read the text section of the module. For Bareflank... that approach would not work as Bareflank loads itself into executable memory, and then manages everything from there. I think this is also how VMWare works IIRC. 

I think the only thing we need is the ability to flip the VMX bit in CR4 and map executable memory. The issue is that they are talking about preventing executable memory. That would be a pretty breaking change. Wouldn't that break all sorts of things, including modules like nVidia's driver, as well as other firmware that can be loaded into the kernel? Either way, there are ways for us to deal with this if they go down that path. Bareflank is in the process of moving extensions to Ring 3 in the host instead of everything running in Ring 0. This is to make extension writing easier, with less stuff that Bareflank has to manage. We could load the kernel portion of Bareflank before Linux, allowing us to load extensions, and reload them as needed after Linux is running. 

IMO, they haven't through this all the way through. If this is just to ensure that an out-of-tree hypervisor has the proper changes needed to support new features in Linux, this is really heavy handed way of doing it, that we can bypass one way or another, without actually addressing the thing that needs to be fixed. If this is to prevent modules from attacking the kernel... that's a waste of time. 

The thread seems to stop without a resolution. Is there another thread where people are talking that discusses what we will have to do to support this moving forward? Ideally:
- We would have to address the SLD issue, like all other hypervisors. This is easy enough to deal with. 
- We would add the SLD flag to the module. Once we do that, we are allowed to flip the VMX bit, run VMX instructions, and map in executable memory. If we don't add the flag, these would be detected and would prevent us from loading, which is fine. I see no issues with being forced to add support for SLD and then telling Linux that we are cool... so long as once we do, things continue to work as expected. If they just start shutting this stuff down without a way to still function.... that would really suck and would force us to implement the approaches above which would bypass the whole point of the patch in the first place.

**Comment by andyhhp** [comment]
For CR access, the intention was to only permit modules to use properly exported interfaces for doing sensitive operations, which e.g. include pinned-bits logic to prevent ROP gadgets from clearing CR0.WP or CR4.{SMEP,SMAP,etc}.  This was checked by disassembling the module .text and seeing which instructions it uses.

Things move quickly on LKML, and right now, the CR/DR restrictions aren't feasible to go in in the their current form.  I'd ignore them for now, and focus on just the Splitlock aspect, which is a real issue.

Linux will aggressively turn splitlock #AC's on, which manifests as a backwards incompatible change inside the guest.  Hypervisors need to intercept #AC unconditionally to mitigate CVE-2015-5307, so you are in a position to attempt to do something to stop the guest crashing.
